### ISSUE TITLE
[🛠️REFACT] Entity클래스에 @Setter가 필요할까요?

### ISSUE THREAD

**Issue by eundeang** [Dongguk-founder/ERA-Backend#9]
# Desciption

본 프로젝트의 구조는 DTO가 존재하므로, Entity가 계층간의 데이터 전달을 위해 사용되는 객체가 아니다. 
또한 서비스 클래스와 비즈니스 로직들이 Entity 클래스 기준으로 동작하기 때문에 Entity 변경으로 여러 클래스에 영향을 미칠 수 있다.
띠리서 객체의 일관성, 안정성을 보장하기 위해 setter 메소드 사용을 지양하는 것이 좋다고 판단하였다.

# Conclusion

setter메소드 대신에 constructor나 builder를 사용하는 것이 좋을 것 같다.

**Comment by ocean010315** [comment]
entity에 있는 dto를 entity로 바꾸는 메소드에서 setter를 없애고 @Builder를 사용합시다. Constructor는 entity를 다른 클래스에서 호출할 때 바로 생성되어 버리므로!!
